import bcrypt from "bcryptjs";
const data = {
    users: [{
            name: "Hari",
            email: "hari@gmail.com",
            password: bcrypt.hashSync("123456"),
            isAdmin: true,
        }
    ],
    products: [{
            // _id: "1",
            name: "Nike Slim Shirt",
            slug: "nike-slim-shirt",
            category: "Shirts",
            image: "/assets/p1.jpg",
            price: 120,
            countInStocks: 0,
            brand: "Nike",
            rating: 4.5,
            numReviews: 10,
            description: "high quality shirt",
        },
        {
            // _id: "2",
            name: "Adidas Fit Shirt",
            slug: "adidas-fit-shirt",
            category: "Shirts",
            image: "/assets/p2.jpg",
            price: 250,
            countInStocks: 20,
            brand: "Adidas",
            rating: 4.0,
            numReviews: 10,
            description: "high quality product",
        },
        {
            // _id: "3",
            name: "Nike Slim Pant",
            slug: "nike-slim-pant",
            category: "Pants",
            image: "/assets/p3.jpg",
            price: 25,
            countInStocks: 15,
            brand: "Nike",
            rating: 4.5,
            numReviews: 14,
            description: "high quality shirt",
        },
        {
            // _id: "4",
            name: "Adidas Fit Pant",
            slug: "adidas-fit-pant",
            category: "Pants",
            image: "/assets/p4.jpg",
            price: 65,
            countInStocks: 5,
            brand: "Puma",
            rating: 4.0,
            numReviews: 10,
            description: "high quality product",
        },
    ],
};

export default data;